### ISSUE TITLE
run-ios出错

### ISSUE THREAD

**Issue by AntHuiZi** [zhouwei1994/nativeCase#3]
error: bundling failed: Error: Unable to resolve module `../view/home/DatePicker` from `/Users/zhangminghui/Downloads/nativeCase-master/src/router/index.js`: The module `../view/home/DatePicker` could not be found from `/Users/zhangminghui/Downloads/nativeCase-master/src/router/index.js`. Indeed, none of these files exist:
  * `/Users/zhangminghui/Downloads/nativeCase-master/src/view/home/DatePicker(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users/zhangminghui/Downloads/nativeCase-master/src/view/home/DatePicker/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
    at ModuleResolver.resolveDependency (/Users/zhangminghui/Downloads/nativeCase-master/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:120:15)
    at ResolutionRequest.resolveDependency (/Users/zhangminghui/Downloads/nativeCase-master/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:49:18)
    at DependencyGraph.resolveDependency (/Users/zhangminghui/Downloads/nativeCase-master/node_modules/metro/src/node-haste/DependencyGraph.js:218:16)
    at Object.resolve (/Users/zhangminghui/Downloads/nativeCase-master/node_modules/metro/src/lib/transformHelpers.js:141:30)
    at dependencies.map.result (/Users/zhangminghui/Downloads/nativeCase-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:373:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/zhangminghui/Downloads/nativeCase-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:369:18)
    at /Users/zhangminghui/Downloads/nativeCase-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:188:33
    at Generator.next (<anonymous>)
    at step (/Users/zhangminghui/Downloads/nativeCase-master/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:30)

**Comment by AntHuiZi** [comment]
Failed to load bundle(http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false) with error:(Unable to resolve module `../view/home/DatePicker` from `/Users/zhangminghui/Downloads/nativeCase-master/src/router/index.js`: The module `../view/home/DatePicker` could not be found from `/Users/zhangminghui/Downloads/nativeCase-master/src/router/index.js`. Indeed, none of these files exist:
  * `/Users/zhangminghui/Downloads/nativeCase-master/src/view/home/DatePicker(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)`
  * `/Users/zhangminghui/Downloads/nativeCase-master/src/view/home/DatePicker/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)` (null))
